Revert "URL-encode values passed to /_synapse/admin/v1/users/{id}/login"
This reverts commit 0d4b597c1a1fabe1da42c63020fc4217c3db70ca.

Turns out that URL-encoding the user id leads to Synapse errors like this:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
>     result = current_context.run(gen.send, result)
> StopIteration: 1
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/synapse/http/server.py", line 368, in _async_render_wrapper
>     callback_return = await self._async_render(request)
>   File "/usr/local/lib/python3.9/site-packages/synapse/http/server.py", line 574, in _async_render
>     callback_return = await raw_callback_return
>   File "/usr/local/lib/python3.9/site-packages/synapse/rest/admin/users.py", line 926, in on_POST
>     if not self.is_mine_id(user_id):
>   File "/usr/local/lib/python3.9/site-packages/synapse/server.py", line 343, in is_mine_id
>     return string.split(":", 1)[1] == self.hostname
> IndexError: list index out of range